packages:
  - 'packages/*'
  - 'packages/runtime/*'
  - 'docs'
  - 'example'
  - 'example/packages/display'
  - 'example/packages/edit'
  - 'example/packages/manifest'
  - 'example/packages/server'

onlyBuiltDependencies:
  - sqlite3
