packages:
  - 'packages/*'
  - 'packages/runtime/*'
  - 'docs'
  - 'example/tailor'
  - 'example/tailor-next'
  - 'example/tailor/packages/display'
  - 'example/tailor/packages/edit'
  - 'example/tailor/packages/manifest'
  - 'example/tailor/packages/server'
  - 'example/tailor-next/packages/display'
  - 'example/tailor-next/packages/edit'
  - 'example/tailor-next/packages/manifest'
  - 'example/tailor-next/packages/server'
